name: Linting, formatting and Build on PR

on:
    push:
        branches: [main, dev]
        paths: 
            -   "frontend/**"
    pull_request:
        branches: [main, dev]
    workflow_dispatch:

jobs:
    lint-and-build-frontend:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: frontend

        steps:
        -   name: Checkout the Repository
            uses: actions/checkout@v3

        -   uses: actions/setup-node@v4
            with:
                node-version: 20

        -   name: Install dependencies
            run: npm install --legacy-peer-deps

        -   name: Run linting check
            run: npm run lint:check

        -   name: Run formatting check
            run: npm run format:check

        -   name: Build
            run: npm run build